name: update-tap

on:
  schedule:
    # Run at beginning of every hour
    - cron: "0 * * * *"

jobs:
  update-tap:
    runs-on: macos-latest
    steps:
      - name: Update Homebrew formulae
        uses: dawidd6/action-homebrew-bump-formula@master
        with:
          # Requires personal access token
          token: "${{ secrets.TOKEN }}"
          tap: jozhw/executor
          force: false
          livecheck: true
